runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /(.*\.(js|css|svg|png)(|\.map))$
  static_files: dist/indiangadget/\1
  upload: dist/indiangadget/(.*)(|\.map)
- url: /.*
  static_files: dist/indiangadget/index.html
  upload: dist/indiangadget/.*
# - url: /
#   secure: always
#   static_files: dist/indiangadget/index.html
#   upload: dist/indiangadget/index.html
# - url: /
#   secure: always
#   static_dir: dist/indiangadget

skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
  